from django.db import models


# Create your models here.
class XiaoMaiDao(models.Model):
    Station = models.CharField(max_length=10, null=True)
    Year = models.CharField(max_length=4, null=True)
    Month = models.CharField(max_length=2, null=True)
    Day = models.CharField(max_length=2, null=True)
    Hour = models.CharField(max_length=2, null=True)
    Lat = models.CharField(max_length=10, null=True)
    Long = models.CharField(max_length=10, null=True)
    Visibility = models.CharField(max_length=10, null=True)
    Air_Temperature = models.CharField(max_length=10, null=True)
    Wind_direction = models.CharField(max_length=10, null=True)
    Wind_speed = models.CharField(max_length=10, null=True)
    Atmospheric_Pressure = models.CharField(max_length=10, null=True)
    During_Past_6_hours_Precipitation = models.CharField(max_length=10, null=True)
    Sea_Temperature = models.CharField(max_length=10, null=True)
    Wind_Wave_Height = models.CharField(max_length=10, null=True)
    Wind_Wave_Period = models.CharField(max_length=10, null=True)
    Surge_Height = models.CharField(max_length=10, null=True)
    Surge_Period = models.CharField(max_length=10, null=True)
    filename = models.CharField(max_length=20, null=True)


class ZhiFuDao(models.Model):
    Station = models.CharField(max_length=10, null=True)
    Year = models.CharField(max_length=4, null=True)
    Month = models.CharField(max_length=2, null=True)
    Day = models.CharField(max_length=2, null=True)
    Hour = models.CharField(max_length=2, null=True)
    Lat = models.CharField(max_length=10, null=True)
    Long = models.CharField(max_length=10, null=True)
    Visibility = models.CharField(max_length=10, null=True)
    Air_Temperature = models.CharField(max_length=10, null=True)
    Wind_direction = models.CharField(max_length=10, null=True)
    Wind_speed = models.CharField(max_length=10, null=True)
    Atmospheric_Pressure = models.CharField(max_length=10, null=True)
    During_Past_6_hours_Precipitation = models.CharField(max_length=10, null=True)
    Sea_Temperature = models.CharField(max_length=10, null=True)
    Wind_Wave_Height = models.CharField(max_length=10, null=True)
    Wind_Wave_Period = models.CharField(max_length=10, null=True)
    Surge_Height = models.CharField(max_length=10, null=True)
    Surge_Period = models.CharField(max_length=10, null=True)
    filename = models.CharField(max_length=20, null=True)


class BeiShuang(models.Model):
    Station = models.CharField(max_length=10, null=True)
    Year = models.CharField(max_length=4, null=True)
    Month = models.CharField(max_length=2, null=True)
    Day = models.CharField(max_length=2, null=True)
    Hour = models.CharField(max_length=2, null=True)
    Lat = models.CharField(max_length=10, null=True)
    Long = models.CharField(max_length=10, null=True)
    Visibility = models.CharField(max_length=10, null=True)
    Air_Temperature = models.CharField(max_length=10, null=True)
    Wind_direction = models.CharField(max_length=10, null=True)
    Wind_speed = models.CharField(max_length=10, null=True)
    Atmospheric_Pressure = models.CharField(max_length=10, null=True)
    During_Past_6_hours_Precipitation = models.CharField(max_length=10, null=True)
    Sea_Temperature = models.CharField(max_length=10, null=True)
    Wind_Wave_Height = models.CharField(max_length=10, null=True)
    Wind_Wave_Period = models.CharField(max_length=10, null=True)
    Surge_Height = models.CharField(max_length=10, null=True)
    Surge_Period = models.CharField(max_length=10, null=True)
    filename = models.CharField(max_length=20, null=True)


class DaChen(models.Model):
    Station = models.CharField(max_length=10, null=True)
    Year = models.CharField(max_length=4, null=True)
    Month = models.CharField(max_length=2, null=True)
    Day = models.CharField(max_length=2, null=True)
    Hour = models.CharField(max_length=2, null=True)
    Lat = models.CharField(max_length=10, null=True)
    Long = models.CharField(max_length=10, null=True)
    Visibility = models.CharField(max_length=10, null=True)
    Air_Temperature = models.CharField(max_length=10, null=True)
    Wind_direction = models.CharField(max_length=10, null=True)
    Wind_speed = models.CharField(max_length=10, null=True)
    Atmospheric_Pressure = models.CharField(max_length=10, null=True)
    During_Past_6_hours_Precipitation = models.CharField(max_length=10, null=True)
    Sea_Temperature = models.CharField(max_length=10, null=True)
    Wind_Wave_Height = models.CharField(max_length=10, null=True)
    Wind_Wave_Period = models.CharField(max_length=10, null=True)
    Surge_Height = models.CharField(max_length=10, null=True)
    Surge_Period = models.CharField(max_length=10, null=True)
    filename = models.CharField(max_length=20, null=True)


class DongShan(models.Model):
    Station = models.CharField(max_length=10, null=True)
    Year = models.CharField(max_length=4, null=True)
    Month = models.CharField(max_length=2, null=True)
    Day = models.CharField(max_length=2, null=True)
    Hour = models.CharField(max_length=2, null=True)
    Lat = models.CharField(max_length=10, null=True)
    Long = models.CharField(max_length=10, null=True)
    Visibility = models.CharField(max_length=10, null=True)
    Air_Temperature = models.CharField(max_length=10, null=True)
    Wind_direction = models.CharField(max_length=10, null=True)
    Wind_speed = models.CharField(max_length=10, null=True)
    Atmospheric_Pressure = models.CharField(max_length=10, null=True)
    During_Past_6_hours_Precipitation = models.CharField(max_length=10, null=True)
    Sea_Temperature = models.CharField(max_length=10, null=True)
    Wind_Wave_Height = models.CharField(max_length=10, null=True)
    Wind_Wave_Period = models.CharField(max_length=10, null=True)
    Surge_Height = models.CharField(max_length=10, null=True)
    Surge_Period = models.CharField(max_length=10, null=True)
    filename = models.CharField(max_length=20, null=True)
