# Generated by Django 3.0 on 2023-09-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbop', '0002_auto_20230901_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='beishuang',
            name='Air_Temperature',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='beishuang',
            name='Atmospheric_Pressure',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='beishuang',
            name='Day',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='beishuang',
            name='During_Past_6_hours_Precipitation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='beishuang',
            name='Hour',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='beishuang',
            name='Lat',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='beishuang',
            name='Long',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='beishuang',
            name='Month',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='beishuang',
            name='Sea_Temperature',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='beishuang',
            name='Station',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='beishuang',
            name='Surge_Height',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='beishuang',
            name='Surge_Period',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='beishuang',
            name='Visibility',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='beishuang',
            name='Wind_Wave_Height',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='beishuang',
            name='Wind_Wave_Period',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='beishuang',
            name='Wind_direction',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='beishuang',
            name='Wind_speed',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='beishuang',
            name='Year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='beishuang',
            name='filename',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dachen',
            name='Air_Temperature',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dachen',
            name='Atmospheric_Pressure',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dachen',
            name='Day',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='dachen',
            name='During_Past_6_hours_Precipitation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dachen',
            name='Hour',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='dachen',
            name='Lat',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dachen',
            name='Long',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dachen',
            name='Month',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='dachen',
            name='Sea_Temperature',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dachen',
            name='Station',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dachen',
            name='Surge_Height',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dachen',
            name='Surge_Period',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dachen',
            name='Visibility',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dachen',
            name='Wind_Wave_Height',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dachen',
            name='Wind_Wave_Period',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dachen',
            name='Wind_direction',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dachen',
            name='Wind_speed',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dachen',
            name='Year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='dachen',
            name='filename',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dongshan',
            name='Air_Temperature',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dongshan',
            name='Atmospheric_Pressure',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dongshan',
            name='Day',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='dongshan',
            name='During_Past_6_hours_Precipitation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dongshan',
            name='Hour',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='dongshan',
            name='Lat',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dongshan',
            name='Long',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dongshan',
            name='Month',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='dongshan',
            name='Sea_Temperature',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dongshan',
            name='Station',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dongshan',
            name='Surge_Height',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dongshan',
            name='Surge_Period',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dongshan',
            name='Visibility',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dongshan',
            name='Wind_Wave_Height',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dongshan',
            name='Wind_Wave_Period',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dongshan',
            name='Wind_direction',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dongshan',
            name='Wind_speed',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dongshan',
            name='Year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='dongshan',
            name='filename',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='xiaomaidao',
            name='Air_Temperature',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='xiaomaidao',
            name='Atmospheric_Pressure',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='xiaomaidao',
            name='Day',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='xiaomaidao',
            name='During_Past_6_hours_Precipitation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='xiaomaidao',
            name='Hour',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='xiaomaidao',
            name='Lat',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='xiaomaidao',
            name='Long',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='xiaomaidao',
            name='Month',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='xiaomaidao',
            name='Sea_Temperature',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='xiaomaidao',
            name='Station',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='xiaomaidao',
            name='Surge_Height',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='xiaomaidao',
            name='Surge_Period',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='xiaomaidao',
            name='Visibility',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='xiaomaidao',
            name='Wind_Wave_Height',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='xiaomaidao',
            name='Wind_Wave_Period',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='xiaomaidao',
            name='Wind_direction',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='xiaomaidao',
            name='Wind_speed',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='xiaomaidao',
            name='Year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='xiaomaidao',
            name='filename',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='zhifudao',
            name='Air_Temperature',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='zhifudao',
            name='Atmospheric_Pressure',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='zhifudao',
            name='Day',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='zhifudao',
            name='During_Past_6_hours_Precipitation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='zhifudao',
            name='Hour',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='zhifudao',
            name='Lat',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='zhifudao',
            name='Long',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='zhifudao',
            name='Month',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='zhifudao',
            name='Sea_Temperature',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='zhifudao',
            name='Station',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='zhifudao',
            name='Surge_Height',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='zhifudao',
            name='Surge_Period',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='zhifudao',
            name='Visibility',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='zhifudao',
            name='Wind_Wave_Height',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='zhifudao',
            name='Wind_Wave_Period',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='zhifudao',
            name='Wind_direction',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='zhifudao',
            name='Wind_speed',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='zhifudao',
            name='Year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='zhifudao',
            name='filename',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
